const coffeeDataDev = {
    ol: [
        {
            sku: '7854.80',
            name: '바닐라향* 커피',
            properties: [-4, -4],
            headline: '실키한 부드러움이 위안을 주는 커피',
            icon: '/ecom/medias/sys_master/public/17432224301086/C-1062-MediaRecipeForeground.png',
            category: '바리스타 크리에이션',
            capsuleProductAromatics: ['비스킷향', '곡물향', '바닐라향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7859.80',
            name: '초콜릿향* 커피',
            properties: [-4, -2],
            headline: '나를 채우는 풍성한 만족감을 주는 커피',
            icon: '/ecom/medias/sys_master/public/17431321215006/C-1060-MediaRecipeForeground.png',
            category: '바리스타 크리에이션',
            capsuleProductAromatics: ['초콜릿향', '시리얼향과 몰트향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7860.80',
            name: '캐러멜향* 커피',
            properties: [-4, -3],
            headline: '놀랍도록 크리미한 나를 위한 작은 사치',
            icon: '/ecom/medias/sys_master/public/17431329505310/C-1061-MediaRecipeForeground.png',
            category: '바리스타 크리에이션',
            capsuleProductAromatics: ['캐러멜향', '비스킷향', '견과류향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7858.80',
            name: '헤이즐넛향* 커피',
            properties: [-5, -2],
            headline: '로스티드 헤이즐넛향의 거부할 수 없는 달콤한 휴식',
            icon: '/ecom/medias/sys_master/public/17432560599070/C-1063-MediaRecipeForeground.png',
            category: '바리스타 크리에이션',
            capsuleProductAromatics: ['비스킷향', '곡물향', '헤이즐넛향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7757.40',
            name: '부에노스 아이레스 룽고',
            properties: [-3, -4],
            headline: '단맛이 감도는 캐러멜향의 마일드한 커피',
            icon: '/ecom/medias/sys_master/public/13703698612254/C-0689-Mobile-Recipe-Carousel-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['곡물향', '카라멜향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7879.80',
            name: '비엔나 룽고',
            properties: [-2, -2],
            headline: '부드러운 바디감과 균형감이 뛰어난 맥아향 커피',
            icon: '/ecom/medias/sys_master/public/13703692582942/C-0687-Mobile-Recipe-Carousel-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['시리얼향과 몰트향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7882.80',
            name: '파리',
            properties: [-1, -2],
            headline: '곡물향과 비스킷향이 균형을 이루는 파리지앵 커피',
            icon: '/ecom/medias/sys_master/public/15431403012126/RecipeForegound-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['시트러스향', '곡물향', '비스킷향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7855.80',
            name: '리반토',
            properties: [-3, -2],
            headline: '오랜 시간 미디엄 로스팅한 캐러멜향 커피',
            icon: '/ecom/medias/sys_master/public/12839369211934/Mobile-Recipe-Carousel-192x192.png',
            category: '이스피라치오네 이탈리아나',
            capsuleProductAromatics: ['캐러멜향', '균형감'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7865.80',
            name: '볼루토',
            properties: [2, -4],
            headline: '마일드하고 스윗한 풍미의 곡물향 커피',
            icon: '/ecom/medias/sys_master/public/15769786548254/RecipeForegound-192x192.png',
            category: '에스프레소',
            capsuleProductAromatics: ['균형감', '과일향', '곡물향'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7864.80',
            name: '볼루토 디카페나토',
            properties: [2, -4],
            headline: '마일드하고 스윗한 풍미의 곡물향 디카페인 커피',
            icon: '/ecom/medias/sys_master/public/34682639187998/volluto-OL-MediaRecipeForeground.png',
            category: '디카페인',
            capsuleProductAromatics: ['균형감', '곡물향', '과일향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7588.40',
            name: '코지',
            properties: [3, -4],
            headline: '시트러스향과 곡물향의 조화를 이루는 커피',
            icon: '/ecom/medias/sys_master/public/15769790414878/RecipeForegound-192x192.png',
            category: '에스프레소',
            capsuleProductAromatics: ['곡물향', '시트러스향'],
            inStock: false,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7719.70',
            name: '에티오피아',
            properties: [4, -4],
            headline: '건식 가공의 꽃향',
            icon: '/ecom/medias/sys_master/public/10831339749406/C-0393-ethiopia-product-RecipeForeground-192x192.png',
            category: '마스터 오리진',
            capsuleProductAromatics: ['꽃향', '과일향'],
            inStock: false,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7856.80',
            name: '니카라과',
            properties: [1, -3],
            headline: '꿀처럼 달콤한 풍미의 곡물향 커피',
            icon: '/ecom/medias/sys_master/public/10838078717982/C-0362-nicaragua-product-RecipeForeground-192x192.png',
            category: '마스터 오리진',
            capsuleProductAromatics: ['곡물향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7831.40',
            name: '카프리치오',
            properties: [2, -3],
            headline: '깊고 조화로운 풍미와 섬세한 산미의 조화',
            icon: '/ecom/medias/sys_master/public/15769781993502/RecipeForegound-192x192.png',
            category: '에스프레소',
            capsuleProductAromatics: ['곡물향', '균형감'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7759.40',
            name: '상하이 룽고',
            properties: [3, -3],
            headline: '부드러운 시트러스향의 산미와 베리향이 조화',
            icon: '/ecom/medias/sys_master/public/13704137965598/C-0690-Mobile-Recipe-Carousel-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['시트러스향', '베리향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7892.80',
            name: '키아로',
            properties: [2, -2],
            headline: '우유와 어울리는 비스킷향 커피',
            category: '바리스타 크리에이션',
            capsuleProductAromatics: ['균형감', '은은한 달콤함', '비스킷향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7889.80',
            name: '콜롬비아',
            properties: [3, -2],
            headline: '과즙향의 산뜻한 산미와 와인향을 품은 커피',
            icon: '/ecom/medias/sys_master/public/10842306052126.png',
            category: '마스터 오리진',
            capsuleProductAromatics: ['와인향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7881.80',
            name: '도쿄 룽고',
            properties: [4, -2],
            headline: '섬세한 꽃향에 로스팅향의 부드러운 조화',
            icon: '/ecom/medias/sys_master/public/13753034604574/Mobile-Recipe-Carousel-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['꽃향', '로스팅향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7877.80',
            name: '이스탄불',
            properties: [2, -1],
            headline: '아몬드향의 여운이 남는 로스팅향과 과일향의 조화',
            icon: '/ecom/medias/sys_master/public/15165862150174/RecipeForegound-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['로스팅향', '과일향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7870.80',
            name: '프레도 델리카토',
            properties: [4, -1],
            headline: '향긋한 과일향의 산뜻한 아이스 커피',
            icon: '/ecom/medias/sys_master/public/15388879487006/RecipeForegound-192x192.png',
            category: '아이스 커피',
            capsuleProductAromatics: ['과일향'],
            inStock: true,
            price: 790,
            salesMultiple: 10,
        },
        {
            sku: '7853.80',
            name: '스톡홀름 룽고',
            properties: [-4, 1],
            headline: '깊은 풍미의 맥아향과 로스팅향의 조화',
            icon: '/ecom/medias/sys_master/public/13703619379230/Mobile-Recipe-Carousel-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['로스팅향', '시리얼향과 몰트향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7890.80',
            name: '베네치아',
            properties: [-3, 1],
            headline: '오랜 시간 미디엄 다크로스팅한 로스팅향 커피',
            icon: '/ecom/medias/sys_master/public/15819021942814/C-0472-MediaRecipeForeground.png',
            category: '이스피라치오네 이탈리아나',
            capsuleProductAromatics: ['로스팅향'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7883.80',
            name: '프레도 인텐소',
            properties: [-2, 2],
            headline: '진한 아이스커피에 최적인 고소한 곡물향의 커피',
            icon: '/ecom/medias/sys_master/public/15389398990878/C-0918-RecipeForegound-192x192.png',
            category: '아이스 커피',
            capsuleProductAromatics: ['로스팅향', '곡물향'],
            inStock: true,
            price: 790,
            salesMultiple: 10,
        },
        {
            sku: '7887.80',
            name: '케이프타운 룽고',
            properties: [-4, 3],
            headline: '풍부한 바디감과 우디향의 강도 높은 커피',
            icon: '/ecom/medias/sys_master/public/13702032883742/Mobile-Recipe-Carousel-192x192.png',
            category: '월드 익스플로레이션',
            capsuleProductAromatics: ['로스팅향', '우디향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7891.80',
            name: '스쿠로',
            properties: [-3, 3],
            headline: '우유와 어울리는 로스팅향 커피',
            icon: '/ecom/medias/sys_master/public/13082448592926/Mobile-Recipe-Carousel-192x192.png',
            category: '바리스타 크리에이션',
            capsuleProductAromatics: ['로스팅향', '균형감'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7884.80',
            name: '인디아',
            properties: [-4, 4],
            headline: '우디향의 여운이 남는 스파이시향 커피',
            icon: '/ecom/medias/sys_master/public/10840378245150/C-0359-India-product-RecipeForeground-192x192.png',
            category: '마스터 오리진',
            capsuleProductAromatics: ['스파이시향', '강렬함', '우디향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7868.80',
            name: '카자르',
            properties: [-2, 4],
            headline: '오랜 시간 다크로스팅한 스파이시향 커피',
            icon: '/ecom/medias/sys_master/public/12839073513502/Mobile-Recipe-Carousel-192x192.png',
            category: '이스피라치오네 이탈리아나',
            capsuleProductAromatics: ['우디향', '스파이시향'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7871.80',
            name: '코르토',
            properties: [-4, 5],
            headline: '우유와 어울리는 스파이시향 커피',
            icon: '/ecom/medias/sys_master/public/13082443808798/Mobile-Recipe-Carousel-192x192.png',
            category: '바리스타 크리에이션',
            capsuleProductAromatics: ['스파이시향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7895.80',
            name: '나폴리',
            properties: [-3, 5],
            headline: '오랜 시간 다크로스팅한 강한 로스팅향 커피',
            icon: '/ecom/medias/sys_master/public/15819008737310/C-0471-MediaRecipeForeground.png',
            category: '이스피라치오네 이탈리아나',
            capsuleProductAromatics: ['강렬함', '로스팅향'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7874.80',
            name: '인도네시아',
            properties: [2, 1],
            headline: '싱그러운 열대우림의 우디향 커피',
            icon: '/ecom/medias/sys_master/public/12038945800222/C-0390-indonesia-product-RecipeForeground-192x192.png',
            category: '마스터 오리진',
            capsuleProductAromatics: ['강렬함', '우디향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7861.80',
            name: '로마',
            properties: [3, 1],
            headline: '짧은 시간 라이트로스팅한 우디향 커피',
            icon: '/ecom/medias/sys_master/public/12839358660638/Mobile-Recipe-Carousel-192x192.png',
            category: '이스피라치오네 이탈리아나',
            capsuleProductAromatics: ['우디향', '곡물향'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7888.80',
            name: '아르페지오',
            properties: [2, 2],
            headline: '짧은 시간 다크로스팅으로 완성한 코코아향 커피',
            icon: '/ecom/medias/sys_master/public/12839052738590/Mobile-Recipe-Carousel-192x192.png',
            category: '이스피라치오네 이탈리아나',
            capsuleProductAromatics: ['코코아향', '강한 로스팅향'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7885.80',
            name: '리스트레토',
            properties: [3, 3],
            headline: '로스팅향과 베리향이 조화로운 반전매력의 커피',
            icon: '/ecom/medias/sys_master/public/12824287903774/Mobile-Recipe-Carousel-192x192.png',
            category: '이스피라치오네 이탈리아나',
            capsuleProductAromatics: ['강한 로스팅향', '베리향'],
            inStock: true,
            price: 720,
            salesMultiple: 10,
        },
        {
            sku: '7862.80',
            name: '아르페지오 디카페나토',
            properties: [2, 2],
            headline: '짧은 시간 다크로스팅한 코코아향 디카페인 커피',
            icon: '/ecom/medias/sys_master/public/44096797769758/C-0479-OL-MediaRecipeForeground.png',
            category: '디카페인',
            capsuleProductAromatics: ['코코아향', '강한 로스팅향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
        {
            sku: '7857.80',
            name: '리스트레토 디카페나토',
            properties: [3, 3],
            headline: '로스팅향과 베리향이 조화로운 디카페인 커피',
            icon: '/ecom/medias/sys_master/public/44097662844958/C-0478-OL-MediaRecipeForeground.png',
            category: '디카페인',
            capsuleProductAromatics: ['강한 로스팅향', '베리향'],
            inStock: true,
            price: 750,
            salesMultiple: 10,
        },
    ],
    vl: [
        {
            sku: '7295.60',
            name: '골든 캐러멜향* 커피',
            properties: [-4, -4],
            headline: '나를 위한 작은 사치',
            icon: '/ecom/medias/sys_master/public/17413899288606/C-1067-MediaRecipeForeground.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['캐러멜향', '비스킷향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7292.60',
            name: '스위트 바닐라향* 커피',
            properties: [-3, -4],
            headline: '부드러운 위안',
            icon: '/ecom/medias/sys_master/public/17413157650462/C-1066-MediaRecipeForeground.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['곡물향', '비스킷향', '바닐라향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7016.60',
            name: '비앙코 도피오 포 밀크',
            properties: [-1, -4],
            headline: '우유와 어울리는 부드러움',
            icon: '/ecom/medias/sys_master/public/15922843418654/C-1034-MediaRecipeForeground.png',
            category: '더블 에스프레소 80ml',
            capsuleProductAromatics: ['캐러멜향'],
            inStock: true,
            price: 870,
            salesMultiple: 10,
        },
        {
            sku: '7294.60',
            name: '로스티드 헤이즐넛향* 커피',
            properties: [-4, -2],
            headline: '달콤한 휴식',
            icon: '/ecom/medias/sys_master/public/17395709968414/C-1064-MediaRecipeForeground.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['헤이즐넛향', '견과류향', '은은한 달콤함', '카라멜향', '비스킷향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7296.60',
            name: '리치 초콜릿향* 커피',
            properties: [-3, -2],
            headline: '풍요로운 만족감',
            icon: '/ecom/medias/sys_master/public/17406287577118/C-1065-MediaRecipeForeground.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['곡물향', '초콜릿향', '캐러멜향', '아몬드향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7057.60',
            name: '스위트 바닐라향* 디카페나토',
            properties: [-3, -4],
            headline: '카페인 부담 없이, 달콤한 바닐라향과 함께하는 여유',
            icon: '/ecom/medias/sys_master/public/34718158192670/C-1306-VL-MediaRecipeForeground.png',
            category: '디카페인',
            capsuleProductAromatics: ['바닐라향'],
            inStock: true,
            price: 1150,
            salesMultiple: 10,
        },
        {
            sku: '2116.91',
            name: '스타벅스® 크리미 바닐라향 커피',
            properties: [-3, -3],
            headline: '달콤한 바닐라 & 비스킷향',
            icon: '/ecom/medias/sys_master/public/34034184912926/C-1297-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['바닐라향', '비스킷향'],
            inStock: true,
            price: 1300,
            salesMultiple: 8,
        },
        {
            sku: '2117.91',
            name: '스타벅스® 스무스 캐러멜향 커피',
            properties: [-4, -3],
            headline: '버터리 캐러멜 & 바닐라향',
            icon: '/ecom/medias/sys_master/public/34032686039070/C-1298-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['캐러멜향', '바닐라향'],
            inStock: true,
            price: 1300,
            salesMultiple: 8,
        },
        {
            sku: '7192.60',
            name: '액티브',
            properties: [-2, -3],
            headline: '아이스로 즐기기 좋은 비타민 B6 함유 커피',
            icon: '/ecom/medias/sys_master/public/34719144902686/C-1307-VL-MediaRecipeForeground.png',
            category: '아이스 커피',
            capsuleProductAromatics: ['바닐라와 아몬드향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7063.60',
            name: '비비다',
            properties: [-2, -2],
            headline: '비타민 B12를 함유한 고소한 비스킷향 커피',
            icon: '/ecom/medias/sys_master/public/15519390171166/Mobile-RecipeForegound-192x192.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['비스킷향', '곡물향'],
            inStock: true,
            price: 1200,
            salesMultiple: 10,
        },
        {
            sku: '7039.60',
            name: '멜로지오',
            properties: [-1, -2],
            headline: '부드럽고 균형 잡힌 풍미',
            icon: '/ecom/medias/sys_master/public/10396390785054/RECIPE-MELOZIO-Face.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['마일드'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7023.60',
            name: '멜로지오 디카페나토',
            properties: [-1, -2],
            headline: '부드러운 디카페인',
            icon: '/ecom/medias/sys_master/public/17299416678430/melozio-decaffeinato-2x.png',
            category: '디카페인',
            capsuleProductAromatics: ['구운 곡물의 느낌', '비스킷향'],
            inStock: true,
            price: 1050,
            salesMultiple: 10,
        },
        {
            sku: '7043.60',
            name: '코스타리카',
            properties: [-1, -1],
            headline: '온천수 가공의 맥아향',
            icon: '/ecom/medias/sys_master/public/13415865876510/C-0631-RecipeForeground-192x192.png',
            category: '그랑 룽고 150ml',
            capsuleProductAromatics: ['시리얼향과 몰트향'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7025.60',
            name: '하프 카페나토',
            properties: [-1, -3],
            headline: '달콤한 하프 카페인',
            icon: '/ecom/medias/sys_master/public/10396392882206/RECIPE-HALF-CAFFEINATO-Face.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['마일드'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7024.60',
            name: '솔레리오',
            properties: [3, -5],
            headline: '가벼운 바디감의 과일향',
            icon: '/ecom/medias/sys_master/public/10396391309342/RECIPE-SOLEILO-Face.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['시트러스향'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7047.60',
            name: '볼테소',
            properties: [4, -5],
            headline: '가볍고 달콤한 풍미',
            icon: '/ecom/medias/sys_master/public/10396392095774/RECIPE-VOLTESSO-Face.png',
            category: '리스트레토 25ml & 에스프레소 40ml',
            capsuleProductAromatics: ['마일드'],
            inStock: true,
            price: 770,
            salesMultiple: 10,
        },
        {
            sku: '7014.60',
            name: '이니지오',
            properties: [3, -4],
            headline: '꽃향과 곡물향의 조화',
            icon: '/ecom/medias/sys_master/public/14450303631390/C-0790-Mobile-RecipeForegound-192x192.png',
            category: '그랑 룽고 150ml',
            capsuleProductAromatics: ['꽃향'],
            inStock: true,
            price: 930,
            salesMultiple: 10,
        },
        {
            sku: '7017.60',
            name: '에티오피아',
            properties: [4, -4],
            headline: '건식 가공의 섬세한 꽃향',
            icon: '/ecom/medias/sys_master/public/13415721959454/C-0630-RecipeForeground-192x192.png',
            category: '그랑 룽고 150ml',
            capsuleProductAromatics: ['꽃향'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7066.60',
            name: '진생 딜라이트',
            properties: [1, -3],
            headline: '인삼 추출물을 함유한 달콤한 캐러멜향* 더블 에스프레소 ',
            icon: '/ecom/medias/sys_master/public/26542899920926/C-1073-MediaRecipeForeground.png',
            category: '아이스 커피',
            capsuleProductAromatics: ['인삼향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7044.60',
            name: '더블 에스프레소 돌체',
            properties: [2, -3],
            headline: '부드럽고 달콤한 곡물향',
            icon: '/ecom/medias/sys_master/public/14450970755102/C-0789-Mobile-RecipeForegound-192x192.png',
            category: '더블 에스프레소 80ml',
            capsuleProductAromatics: ['곡물향'],
            inStock: true,
            price: 870,
            salesMultiple: 10,
        },
        {
            sku: '7028.60',
            name: '콜롬비아',
            properties: [3, -3],
            headline: '습식 가공의 와인향',
            category: '머그 230ml',
            capsuleProductAromatics: ['붉은 과일향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7027.60',
            name: '엘살바도르',
            properties: [4, -3],
            headline: '레드 허니 가공의 과일잼향',
            icon: '/ecom/medias/sys_master/public/26582350921758/C-1115-MediaRecipeForeground.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['과일향', '비스킷향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7046.60',
            name: '오라피오',
            properties: [1, -2],
            headline: '달콤하고 균형 잡힌 풍미',
            icon: '/ecom/medias/sys_master/public/14448957259806/C-0787-Mobile-RecipeForegound-192x192.png',
            category: '리스트레토 25ml & 에스프레소 40ml',
            capsuleProductAromatics: ['캐러멜향'],
            inStock: true,
            price: 770,
            salesMultiple: 10,
        },
        {
            sku: '7126.91',
            name: '스타벅스® 블론드 에스프레소 로스트',
            properties: [2, -2],
            headline: '부드러움 & 달콤함',
            icon: '/ecom/medias/sys_master/public/31864827314206/C-1250-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['로스팅향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7133.91',
            name: '스타벅스® 베란다 블렌드',
            properties: [3, -2],
            headline: '구운 맥아 & 베이킹 초콜릿향',
            icon: '/ecom/medias/sys_master/public/31864830591006/C-1251-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['코코아향', '스파이시향', '구운 맥아향', '초콜릿향'],
            inStock: true,
            price: 1150,
            salesMultiple: 8,
        },
        {
            sku: '7018.60',
            name: '아이스 레제로',
            properties: [4, -2],
            headline: '향긋한 과일향의 산뜻한 아이스 커피',
            icon: '/ecom/medias/sys_master/public/15390016176158/C-0919-Mobile-RecipeForegound-192x192.png',
            category: '아이스 커피',
            capsuleProductAromatics: ['과일향'],
            inStock: true,
            price: 870,
            salesMultiple: 10,
        },
        {
            sku: '7013.60',
            name: '아론디오',
            properties: [1, -1],
            headline: '부드럽고 마일드한 곡물향',
            icon: '/ecom/medias/sys_master/public/10396388032542/RECIPE-ARONDIO-Face.png',
            category: '그랑 룽고 150ml',
            capsuleProductAromatics: ['마일드한 시리얼향'],
            inStock: true,
            price: 930,
            salesMultiple: 10,
        },
        {
            sku: '7002.60',
            name: '비앙코 피콜로 포 밀크',
            properties: [-3, 1],
            headline: '우유와 어울리는 달콤함',
            icon: '/ecom/medias/sys_master/public/15915791220766/C-1035-MediaRecipeForeground.png',
            category: '리스트레토 25ml & 에스프레소 40ml',
            capsuleProductAromatics: ['달콤하고 부드러움'],
            inStock: true,
            price: 770,
            salesMultiple: 10,
        },
        {
            sku: '7030.60',
            name: '비앙코 포르테 포 밀크',
            properties: [-4, 2],
            headline: '우유와 어울리는 강렬함',
            icon: '/ecom/medias/sys_master/public/16058299121694/C-0290-MediaRecipeForeground.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['강렬함', '로스팅향', '균형감'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7029.60',
            name: '아이스 포르테',
            properties: [-3, 2],
            headline: '아이스로 좋은 곡물향',
            icon: '/ecom/medias/sys_master/public/15390000054302/C-0920-Mobile-RecipeForegound-192x192.png',
            category: '아이스 커피',
            capsuleProductAromatics: ['강한 로스팅향', '곡물향', '우디향'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7128.91',
            name: '스타벅스® 싱글 오리진 콜롬비아',
            properties: [-2, 2],
            headline: '구운 호두 & 허브향',
            icon: '/ecom/medias/sys_master/public/34044004958238/C-1296-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['허브향', '팝콘향'],
            inStock: true,
            price: 1300,
            salesMultiple: 8,
        },
        {
            sku: '7026.60',
            name: '멕시코',
            properties: [-1, 2],
            headline: '이중 습식 가공의 우디향',
            category: '머그 230ml',
            capsuleProductAromatics: ['우디향', '스파이시향'],
            inStock: true,
            price: 1100,
            salesMultiple: 10,
        },
        {
            sku: '7127.91',
            name: '스타벅스® 파이크 플레이스 로스트',
            properties: [-3, 3],
            headline: '부드러운 초콜릿향',
            icon: '/ecom/medias/sys_master/public/31864841142302/C-1252-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['코코아향', '스파이시향', '초콜릿향'],
            inStock: true,
            price: 1150,
            salesMultiple: 8,
        },
        {
            sku: '7040.60',
            name: '스토미오',
            properties: [-2, 3],
            headline: '풍부하고 강렬한 풍미',
            icon: '/ecom/medias/sys_master/public/10396391571486/RECIPE-STORMIO-Face.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['강렬함'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7059.60',
            name: '포르타도',
            properties: [-1, 3],
            headline: '풍부한 바디감의 강렬한 풍미',
            icon: '/ecom/medias/sys_master/public/10396389736478/RECIPE-FORTADO-Face.png',
            category: '그랑 룽고 150ml',
            capsuleProductAromatics: ['코코아향', '오크우드향'],
            inStock: true,
            price: 930,
            salesMultiple: 10,
        },
        {
            sku: '7015.60',
            name: '포르타도 디카페나토 ',
            properties: [-1, 3],
            headline: '강렬한 풍미의 디카페인',
            icon: '/ecom/medias/sys_master/public/14450308513822/C-0791-Mobile-RecipeForegound-192x192.png',
            category: '디카페인',
            capsuleProductAromatics: ['우디향'],
            inStock: true,
            price: 970,
            salesMultiple: 10,
        },
        {
            sku: '7130.91',
            name: '스타벅스® 카페 베로나',
            properties: [-4, 4],
            headline: '로스티한 달콤함 & 다크 코코아 향',
            icon: '/ecom/medias/sys_master/public/31865798000670/C-1253-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['캐러멜향', '코코아향'],
            inStock: true,
            price: 1150,
            salesMultiple: 8,
        },
        {
            sku: '7042.60',
            name: '인텐소',
            properties: [-3, 4],
            headline: '깊고 진한 풍미',
            icon: '/ecom/medias/sys_master/public/10396390522910/RECIPE-INTENSO-Face.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['캐러멜향과 로스팅향'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7049.60',
            name: '디아볼리토',
            properties: [-2, 4],
            headline: '매우 진하고 강렬한 풍미',
            icon: '/ecom/medias/sys_master/public/10396389212190/RECIPE-DIAVOLITTO-Face.png',
            category: '리스트레토 25ml & 에스프레소 40ml',
            capsuleProductAromatics: ['강렬함'],
            inStock: true,
            price: 770,
            salesMultiple: 10,
        },
        {
            sku: '7048.60',
            name: '알티시오',
            properties: [-1, 4],
            headline: '풍부한 바디감의 코코아향',
            icon: '/ecom/medias/sys_master/public/10396387770398/RECIPE-ALTISSIO-Face.png',
            category: '리스트레토 25ml & 에스프레소 40ml',
            capsuleProductAromatics: ['과일향'],
            inStock: true,
            price: 770,
            salesMultiple: 10,
        },
        {
            sku: '7000.60',
            name: '알티시오 디카페나토',
            properties: [-1, 4],
            headline: '풍부한 바디감의 디카페인',
            icon: '/ecom/medias/sys_master/public/14448960897054/C-0788-Mobile-RecipeForegound-192x192.png',
            category: '디카페인',
            capsuleProductAromatics: ['코코아향'],
            inStock: true,
            price: 800,
            salesMultiple: 10,
        },
        {
            sku: '7125.91',
            name: '스타벅스® 에스프레소 로스트',
            properties: [-4, 5],
            headline: '리치 캐러멜향',
            icon: '/ecom/medias/sys_master/public/31865803079710/C-1254-VL-MediaRecipeForeground.png',
            category: '스타벅스® by 네스프레소 for 버츄오',
            capsuleProductAromatics: ['캐러멜향'],
            inStock: true,
            price: 860,
            salesMultiple: 10,
        },
        {
            sku: '7058.60',
            name: '더블 에스프레소 스쿠로',
            properties: [-3, 5],
            headline: '진하고 강렬한 풍미',
            category: '더블 에스프레소 80ml',
            capsuleProductAromatics: ['코코아향', '스모키향', 'ROBUSTA'],
            inStock: true,
            price: 870,
            salesMultiple: 10,
        },
        {
            sku: '7060.60',
            name: '일카페',
            properties: [-2, 5],
            headline: '강렬함과 부드러움의 조화',
            icon: '/ecom/medias/sys_master/public/14194526093342/Mobile-RecipeForegound-192x192.png',
            category: '리스트레토 25ml & 에스프레소 40ml',
            capsuleProductAromatics: ['곡물향', '우디향'],
            inStock: true,
            price: 770,
            salesMultiple: 10,
        },
        {
            sku: '7041.60',
            name: '오다치오',
            properties: [1, 2],
            headline: '생동감 넘치는 산뜻함',
            icon: '/ecom/medias/sys_master/public/10396391047198/RECIPE-ODACIO-Face.png',
            category: '머그 230ml',
            capsuleProductAromatics: ['강렬함'],
            inStock: true,
            price: 1000,
            salesMultiple: 10,
        },
        {
            sku: '7050.60',
            name: '더블 에스프레소 키아로',
            properties: [1, 3],
            headline: '진하고 와일드한 풍미',
            category: '더블 에스프레소 80ml',
            capsuleProductAromatics: ['우디향'],
            inStock: true,
            price: 870,
            salesMultiple: 10,
        },
        {
            sku: '7010.60',
            name: '리스트레토 클라시코',
            properties: [2, 4],
            headline: '짧지만 강렬한 아라비카 커피 한 잔',
            icon: '/ecom/medias/sys_master/public/27751151894558.png',
            category: '리스트레토 25ml & 에스프레소 40ml',
            capsuleProductAromatics: ['베리향', '강한 로스팅향'],
            inStock: true,
            price: 770,
            salesMultiple: 10,
        },
    ],
};
